### ISSUE TITLE
[New intent] Increase/decrease volume

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1095]
Users should be able to increase or decrease the volume of audio with utterances such as:
* Increase volume
* Decrease volume
* Turn up the volume
* Turn down the volume
* Make it louder
* Make if softer
* Louder

**Comment by jofish** [comment]
Also 

Shut up
Be quiet
Silence

**Comment by danielamormocea** [comment]
@ianb  Can I start working on this?

**Comment by ianb** [comment]
@danielamormocea I don't think we have a technique to change the volume of the computer from the extension, so this isn't ready to implement.

**Comment by farhatcode** [comment]
We can increase/decrease/turn on/turn off volume of HTML Audio/Video object, by using its Audio/Video DOM volume property. Just as the next/previous/play/pause controls are controlled for the web audio/video player in music services.
I can do this. Please assign it to me.

**Comment by awallin** [comment]
@farhatcode give it a try.

**Comment by farhatcode** [comment]
@awallin I'm working on it.
Right now I'm adding volume controls for youtube web player by adding a new intent to adjust volume. 
Increase or decrease volume are fine. But whenever I have to `mute`/`unmute`. The utterance `(mute | unmute)` is caught by `muting.muteTab`/`muting.unmute` intent. This intent mutes/unmute the tab, sound vanishes but the web player's mute/unmute buttons don't reflect that (because they are not supposed to do so). 
Is the `muting.js` intended to provide mute/unmute for reader mode only? 
How can we make the matches more specific so that muting on the music services is always caught by their particular intent. 
Or may I let it caught by the `muting.muteTab`/`muting.unmute` and then check in `muting.js` if the serviceName of the activeTab matches the music services, then send it to `music.js` to be handled?

**Comment by farhatcode** [comment]
Do you think @awallin we should consider to restructure the design for music services? Right now every music service is keeping its own copy of `player.js`, for doing more or less similar tasks. And if there are more music services going to be added, it means more copies of `player.js` will be added on similar pattern.  We can at least make `player.js` more generalised and do the music service specific tasks in the relevant `musicServiceName.js` files.   
If you think this is a feasible idea, may I go ahead and open a new issue for this? that can fall in “code quality” category.

**Comment by awallin** [comment]
@ianb would be the best way to comment on any restructure of the music service.

**Comment by farhatcode** [comment]
When I was working for youtube (i.e. video player), I came with that idea. But when I started working for soundcloud (i.e. audio player), I have come to know that `player.js` functionality is implemented separately for audio and video players. What I was pointing, is already done in `musicService.js` for audio players.
Please ignore my previous comment. There is no need for restructuring.

**Comment by farhatcode** [comment]
Soundcloud is not using any HTMLMediaElement to play music. It is done somewhere from js code. I tried it many ways, but was unable to access/manipulate the volume property of audio. 
I have simulated the shortcut key for volumeup and volumedown for soundcloud. @ian can you suggest any better ways to do that? Or is it fine this way?

**Comment by farhatcode** [comment]
@ianb May you create a new issue for adding volume controls for spotify? 
I was unable to add that because of service unavailable in my country.
