### ISSUE TITLE
Document normal console errors

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1120]
In the README we should not the console errors that aren't concerning. Especially the manifest errors, and some hint at what kind of errors aren't about us.

**Comment by mohinderps** [comment]
Hey @ianb, I would like to want to work on this. If that's okay with you, can you give me some more details on the issue ?

**Comment by ianb** [comment]
This should just be an update to the README.md file in the development section. If you look at the browser console you'll errors like this:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/44390/75570855-a8288280-5a1d-11ea-9b78-71aceca2ecd5.png">

But these are all OK and normal. Also usually any error that comes from a file that ends with `.jsm` is not related to us, for example:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/44390/75570936-cb533200-5a1d-11ea-93a2-2f1dd2853c87.png">

**Comment by mohinderps** [comment]
So we just need to write in the README file that these kind of errors are normal and users should not be worried about them.

Is that it ?

**Comment by mohinderps** [comment]
@ianb , there are two more things that i noticed while starting the application:

1. Minimum node version must be specified. I was running the project with node v10, so the postintall script was failiing because Array.prototype.flat is not supported by this node version. So i had to update it to node v12.16.1(LTS)

2. When we install firefox nightly, it is installed as 'Firefox Nightly' in the Applications folder in MAC. In this case web-ext is unable to spawn the firefox because it is actually looking for 'FirefoxNightly'(without space). So after installation, the application should be renamed to 'FirefoxNightly' from 'Firefox Nightly'.

**Comment by ianb** [comment]
No, we can't actually stop these messages from the console, so this is just to document them.

Your notes on "Firefox Nightly" would also be useful to other people too. Both these could go in README.md. Thanks!

**Comment by mohinderps** [comment]
Okay. On it. Thanks.
