### ISSUE TITLE
What's playing cleanup & improvments

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1266]
Follow on from #1111 there are some visual improvements that can be made along with education on other audio features that can be used. See attached mockups. A few details to note:

* As quickly as possible card should transition from checkmark with transcription to displaying the result.
* Favicon from tab playing audio should be used as an image.
* Add feedback and education section with the following text
**  Click mic and say ‘pause’, ‘next’ or ‘stop’

![whats-playing](https://user-images.githubusercontent.com/428245/76588885-81e6f600-64a5-11ea-8615-1cfcb46680bb.jpg)

**Comment by AlejandroRdzLpz** [comment]
Can I get this issue assigned, please? I'm an Outreachy applicant

**Comment by awallin** [comment]
Go for @AlejandroRdzLpz

**Comment by awallin** [comment]
Made a few changes to the content and visual layout for this to establish a template for Q&A cards used in #1267  #1270 and #1269. Specs for these cards are as follows:

* 100x100 image
* 25px of padding between Question Transcript and image
* 35px of padding between image and Answer text

**Comment by AlejandroRdzLpz** [comment]
@awallin I was wondering if you could help me mentoring me through this project, I was fiddling with the code yesterday and today and I can't get to make some improvements. I mean, I was able to change some things, but i got lost into the transitions and the favicon extractor.

I sent you a message via Riot. Or if you can point me to another mentor, it would be awesome.

**Comment by awallin** [comment]
@AlejandroRdzLpz I'll hand off to @ianb for mentoring as he's more familiar with the code than I am.

**Comment by ianb** [comment]
@AlejandroRdzLpz Right now we have more Outreachy applicants than we can really handle, and have marked this project as closed to new Outreachy submissions. Of course you are welcome to contribute, but we're pretty much filled up for applicants.

**Comment by saucekode** [comment]
@ianb and @awallin would love to try this out. Thanks

**Comment by ianb** [comment]
@saucekode You got it

**Comment by saucekode** [comment]
@awallin you said to use favicons for the image but it comes out blurry since it's a favicon. @ianb what do you think would be a better option?

**Comment by awallin** [comment]
A few of thoughts.
* Display the image at the native size for favicons (most commonly 16x16 or 32x32)
* Look highest res versions of the favicon and display at it's native size (with a max size of 100x100). Some sites have 48x48, 96x96, and even 144x144 sizes.
* We could use the logo for each music service which we support, which will be added in #1268. While this won't scale to every site that could be playing audio it's likely to account for the majority.

**Comment by saucekode** [comment]
Okay! will do that. Thank you for this

**Comment by ianb** [comment]
For the icon there's a favicon attribute on tabs: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab (`favIconUrl`). Note it can be null.

But maybe we should add icon detection to `pageMetadata-contentScript.js` – then it would be able to find higher-resolution icons. But Spotify for instance only has 32x32 as `<link rel="icon">`, though in the file linked to from `<link rel=manifest>` it has higher resolution icons. YouTube has some bigger sizes.

To find the icons basically look for `link[rel*='icon']` and check for the `size` attribute to guess the size, with a default of 16x16. Maybe it's best to use `max-height` and `max-width` instead of forcing a width and height, and then if we can only get a small icon at least the icon won't be blurry... small seems better than blurry.
