### ISSUE TITLE
"Play previous" not working for Youtube videos

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1338]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
Autoplay is enabled.
Have a Youtube tab open and active. Have several videos played in the tab, before performing the steps bellow.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Play previous", "Previous song" or "Play previous video" command.

### Expected result:
The previous video starts playing.

### Actual result:
"YouTube cannot do "play previous"" is displayed in the doorhanger.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
Reproduced also if the command is made in a Youtube tab that plays a playlist which has "previous", "next" buttons. (2nd gif) If the video plays more than 3 seconds, the "Previous" button needs to be clicked 2 times in order to go to the previous song.

![5](https://user-images.githubusercontent.com/54401091/77077143-82c7dc80-69fd-11ea-8038-0db039f27f08.gif)

![6](https://user-images.githubusercontent.com/54401091/77076724-e00f5e00-69fc-11ea-909f-0f082b925c61.gif)

**Comment by JanviMahajan14** [comment]
I would like to work on this issue.

**Comment by danielamormocea** [comment]
@alexandra-martin   I've looked into this and the reason it displays the message "Youtube cannot do play previous" is because there is no "previous" button on Youtube, just the button for "next video" (I think the previous video can only pe accessed through double taps on the phone app). 

However, if the user wants to go back to the previous video, they can say "go back" and this will load the previous page; (similarly to clicking the top left corner, back arrow button). Should this behaviour be borrowed for the youtube's "play previous" also?

**Comment by awallin** [comment]
@danielamormocea leveraging "go back" is a nice solution for "previous" in this case.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-31).

![2](https://user-images.githubusercontent.com/54401091/78119211-c0226600-7410-11ea-8e18-efd4ec649786.gif)
