### ISSUE TITLE
Toggle switches from "Firefox Voice Data Collection and Use" are depended to one another in some cases

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1342]
### Prerequisites:
Mic permissions are enabled.
"Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
The "Preferences" page is opened and made active (click mic icon and select "Settings" button from doorhanger).

### STR:
1. On the "Preferences" page scroll down to the "Firefox Voice Data Collection and Use" section.
2. Click on the toggle switches several times.

### Expected result:
Toggle switches are independent from one another.

### Actual result:
When the first 2 toggle switches are turned on, by clicking on the first toggle switch, both the first and the second toggle switch will turn off.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-19).
When the first 2 toggle switches are turned off, by clicking on the second toggle switch, both the first and the second toggle switch will turn on.

![15](https://user-images.githubusercontent.com/54401091/77088785-a1ce6a80-6a0d-11ea-875b-365eb98a5420.gif)

**Comment by GangaChatrvedi** [comment]
I would like to work on it

**Comment by GangaChatrvedi** [comment]
@alexandra-martin I was taking a look at the code and then I cam back to look at the text corresponding to radio buttons.

These seems to be pointers that are being followed:
- Permission 1 is mandatory for permission 2.

Because of that. These are some generally unexpected are part of code:
- If both 1 and 2 are off. Turning on 2 will turn on 1.
- If both 1 and 2 are on. Turning off 1 will turn off 2.

**Comment by GangaChatrvedi** [comment]
@ianb can you please verify what I said above is correct. If so, we can close this issue.

**Comment by alexandra-martin** [comment]
@GangaChatrvedi thank you, what you said is right. Will close the bug as invalid.
