### ISSUE TITLE
"Search openstreetmap for London" command makes a Google search

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1421]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Search openstreetmap for London" command.

### Expected result:
Openstreetmap opens in a new tab and a search for "London" is made.

### Actual result:
A Google search is made in a new tab for "openstreetmap for London".

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-30).

![7](https://user-images.githubusercontent.com/54401091/77938484-74f83e00-72be-11ea-9871-c65720e74b38.gif)

**Comment by Simpcyclassy** [comment]
I will like to work on this @ianb

**Comment by awallin** [comment]
I was able to get "search open street maps" to work but "search open street map" returns a Google search. Can we create an alias for the plural?

**Comment by Simpcyclassy** [comment]
I will love to work on the alias if that will be the fix.

**Comment by awallin** [comment]
It's yours @Simpcyclassy

**Comment by Simpcyclassy** [comment]
One of the things I have seen while looking at this issue is that there is some kinda clash because of similar matching words in `navigation.bangSearch` and the intents in `extension/intents/search`. So first I will suggest that a keyword differentiate these searches. I am not sure what that keyword should be yet. Secondly, the `query` aspect of the command seems like it is going to need some fixing somewhere.

**Comment by Simpcyclassy** [comment]
Further looking into the problem made me realize that only specific services that have been added to `searchServices.toml` can be searched, which explains why you can search `open street maps` and not `open street map` from line 85. This was a bit workaround for just 3 lines code.
