### ISSUE TITLE
[Intermittent] "Doorhanger" doesn't close if no command is made

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#314]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Don't write or say anything and observe the "Doorhanger".

### Expected result:
The "Doorhanger" closes if no command is made.

### Actual result:
The "Doorhanger" displays the "One second ..." and the "Sorry, there was an issue" states and doesn't close only after clicking the "x" button or after pressing the "Esc" key.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Reproduced 10/10 times on Win. On Mac the bug is reproduced 7/10 times, but I managed to reproduce it also 10/10 times.

![62](https://user-images.githubusercontent.com/54401091/65521934-a7317900-def2-11e9-96f2-6457a259c0ae.gif)

**Comment by ianb** [comment]
This is because sometimes the voice-detection code tells us there was no sound (and then we close the popup automatically), but sometimes it doesn't. When we think there might have been sound we send the audio to the server, and currently (per #99) the server gives us a 500 error when it gets silent audio.

We should re-verify this once the server is fixed, but I think the server fix will fix this problem.

**Comment by lelouchB** [comment]
@ianb  I would like to work on this

**Comment by ianb** [comment]
@lelouchB I think this is already fixed and we just forgot to close it.
