### ISSUE TITLE
Add feedback for last experience

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#316]
Implement UI to gather feedback on the quality of previous interaction.

![feedback](https://user-images.githubusercontent.com/428245/65530920-b3471780-dead-11e9-8c37-7cd64544468b.jpg)
![listen](https://user-images.githubusercontent.com/428245/65530921-b3471780-dead-11e9-8993-09eb844f7cca.jpg)

**Comment by ianb** [comment]
We want to have thumbs-up/thumbs-down in the popup, that will apply to the previous intent. This should send feedback using `telemetry.sendFeedback({rating: 1/-1})`

**Comment by ianb** [comment]
I've started implementation, some questions for @awallin:

1. Does the feedback form open up if you click either smiley or frowny? If it doesn't, then what happens when you click smiley?
2. How long ago can an intent be and we still show it? 24 hours? 36? 60 minutes?
3. I am assuming the feedback is sent regardless of whether you add feedback text
4. What happens after submit? I'm assuming a thank you of some sort, then it self-closes after a couple seconds.

**Comment by awallin** [comment]
Good questions.

1. The feedback form only opens if you click the frowny. When clicking smiley the icon changes to blue but no other action is taken in the doorhanger (it stays open so the user can issue a voice interaction).
2. How about 24 hours for accepting feedback.
3. Yes, feedback is sent even if you don't add text.
4. After submit let's show the checkmark with "Thanks for your feedback"

Do you need any assets/icons?
