### ISSUE TITLE
What implies support for Spotify?

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#327]
Can you tell me what support for an audio/video platform implies? Found some bugs related to the "Play" command for Spotify, Youtube etc., like "Play Green Day on Youtube", or "Play Green Day", and I want to make sure if I should log them now or later on.

**Comment by awallin** [comment]
@ian and I discussed this yesterday. Over the next week or so we are looking to implement the following:
* Play [artist|song|music genres] on [service] (if a tab for the service already exists it should play from the existing tab but not make it the active tab)
* Play [artist|song|music genres] (if active tab is a music service it should play using that tab otherwise it will auto select (based on history) your most commonly used music service in a new tab and start playing)
* Pause|Stop
* Mute
* Next|Skip|Next song

Related issues include #322 #321 #320 #319 #318 #317 #325

**Comment by ianb** [comment]
Right now Spotify support isn't complete, and we haven't implemented all the commands, and we also haven't made things consistent with the old YouTube (or Reader Mode) code

**Comment by ianb** [comment]
I think @awallin's comment covers our expectations.
