### ISSUE TITLE
"Play Spotify" command plays "ヒプノシスRADIO -Spotify Edition-" podcast

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#471]
### Prerequisites:
Mic permissions are enabled.
A Spotify tab is made the active tab and the music is paused.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Play Spotify" command.

### Expected result:
The Spotify music is playing again.

### Actual result:
"ヒプノシスRADIO -Spotify Edition-" podcast is searched in the tab and starts playing.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
The "Play music" command works as intended.

![5](https://user-images.githubusercontent.com/54401091/67396452-4b6d1500-f5b0-11e9-9d17-5ce53a4feb32.gif)

**Comment by ianb** [comment]
This is because of a conflict between two intents, the play intent: `play [query]` and the unpause intent: `(unpause | continue | play) [service:musicServiceName]`

The prioritization heuristic doesn't distinguish between the generic `[query]` slot and the more specific `[server:musicServiceName]` intent.

To fix this we'll need to keep track of slot types when compiling expressions, and then rank matches using this information (probably counting any typed slot as 1 character – reasonable, since it is on the order of one character of information (though a fancier option would score types based on how limited their matches were, maybe using floating point numbers).

**Comment by ianb** [comment]
I'm going to mark this as a good first issue, but it's a _hard_ good first issue.

The work is entirely inside `intentParser.js`. You'll have to look at these parts:

To keep track of the slot types, put something here to store slot types in a property on the Matcher object:

https://github.com/mozilla/firefox-voice/blob/1d26885d84a32e6cca34987cdf472a9a2517a025/extension/background/intentParser.js#L70-L80

Then you have to return the slot types with the match, similar to parameters:

https://github.com/mozilla/firefox-voice/blob/1d26885d84a32e6cca34987cdf472a9a2517a025/extension/background/intentParser.js#L36-L41

Then you have to make use of that when deciding on the best match:

https://github.com/mozilla/firefox-voice/blob/1d26885d84a32e6cca34987cdf472a9a2517a025/extension/background/intentParser.js#L222-L236

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![1](https://user-images.githubusercontent.com/54401091/67659520-35bb6f00-f965-11e9-8dc8-7fa7ab83f280.gif)
