### ISSUE TITLE
Make keyboard shortcut configurable

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#560]
There are conflicts sometimes (with Multi-Account containers per #550, and with 1Password per #431). We can't choose a keyboard shortcut that works for everyone, so we should just make it configurable.

This would be a new field in the options page. I think we can just force people to type in the keyboard shortcut syntax per the [commannds documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands)

We might leave `Cmd-.` and make this an additional keyboard shortcut...?

**Comment by bnakamoto** [comment]
I had mostly composed (last night) a reply to @ianb about my feedback about Command-Period being a long-time expected keyboard shortcut on macOS, but it appears that [the original thread is now 404](https://github.com/mozilla/firefox_voice_community/issues/183). @ianb had referenced an issue that referenced this issue in his reply so this seems like the best place to share my follow-up; apologies in advance if not.

I surprisingly haven't been able to find any Apple developer docs about Command-Period. They have [Human Interface Guidelines for Keyboard Shortcuts](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/), but there's only reference to Control-Option-Command-Period (to increase screen contrast, part of [accessibility](https://support.apple.com/en-us/HT204434)). There is evidence that Apple has standardized on Command-Period as a cancel/escape/break operation; for example, in their keyboard shortcut docs for [Music](https://support.apple.com/guide/music/keyboard-shortcuts-mus1019/mac) and [Terminal](https://support.apple.com/guide/terminal/keyboard-shortcuts-trmlshtcts/mac). There's also third party docs such as [this one from OSXDaily](http://osxdaily.com/2014/04/05/cancel-button-keyboard-shortcut-mac-osx/) about Command-Period being a broad "'cancel' feature":

> Command+Period also functions as a broader “cancel” feature throughout OS X beyond just closing out of Open/Save/Print and alert dialogs.

Apple has associated Command-Period with "cancel" on Macs since before Mac OS X/macOS, the System _n_ days. Thus, I hope that the _default_ keyboard shortcut for Firefox Voice is changed to something other than Command-Period.

Thank you!
-Brian

**Comment by ianb** [comment]
Per the original thread disappearing: apparently our comment submission process was flagged as suspicious by GitHub, and all comments made that way were hidden. We're working on getting them back.
