### ISSUE TITLE
Fix find intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#58]
The find intent doesn't seem to work right. It always falls back to a search for me, and I have a hard time constructing the right words to trigger the regex.

**Comment by jcambre** [comment]
this regex might be slightly better: `(?:(?:find|bring me to)\s?(?:my|the)?)\s?((?:(?=tab).*)|(?:.*(?=tab)))`

The problem with the one that's currently in the code is that it has two capturing groups (separated by an OR), but JS always returns both, even if empty. The version above isn't ideal because it'll keep the word "tab" as part of the query if the user says something like "find the tab with puppies on it," but it should be good enough.

**Comment by ianb** [comment]
The new `intentParser.js` allows multiple regexes, so we could just separate these out. Maybe we'll have to tweak how `slots` works to allow per-regex slot names.

**Comment by ianb** [comment]
I think the pattern match has been fixed in... some commit, not sure which.
