### ISSUE TITLE
"Play previous" command not working for Spotify and Youtube tabs

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#624]
### Prerequisites:
Mic permissions and autoplay are enabled.
Have a Spotify or Youtube tab open and active. Have several songs/videos played in the tab.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Play previous" command.

### Expected result:
The previous song/video starts playing.

### Actual result:
Nothing happens.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).

![3](https://user-images.githubusercontent.com/54401091/69964436-17740080-151b-11ea-94df-6f92fb202039.gif)

**Comment by ianb** [comment]
YouTube doesn't have a notion of "previous" (unless maybe the back button), but this should be fixed for Spotify.

**Comment by alexandra-martin** [comment]
There can be a previous button, if videos are in a playlist. But I don't know if this should be applied differently.

**Comment by sheilaanguiano** [comment]
Hi, I'll start reading and working on this one

**Comment by ianb** [comment]
@sheilaanguiano Are you still working on this? If it's not working out I'd like to open this back up for other contributors

**Comment by sheilaanguiano** [comment]
Hi Ian, yes please open it up for others

**Comment by vandnakapoor19** [comment]
@ianb I'd like to check this issue.

**Comment by vandnakapoor19** [comment]
@ianb I did some research about Play previous command and in most of the blogs they have mentioned

**It starts the same song again.**

Please check it out once
https://ios.gadgethacks.com/how-to/use-siri-play-spotify-music-all-commands-you-need-know-0208428/

I've implemented this functionality on my local if we say "Play Previous", then It starts the song again.

Let me know if it is fine or I have to do more research on this issue?

Give your suggestions about this issue.

![Play_previous](https://user-images.githubusercontent.com/45131874/76529818-33a40980-6449-11ea-9732-7971231a9fb0.gif)


Thanks

**Comment by melvin2016** [comment]
I think you could use querySelector().click() to click 2 times.

**Comment by vandnakapoor19** [comment]
@melvin2016  I am not sure why I have to click 2 times. Please let me know what will happen if I'll use querySelector().click().

**Comment by melvin2016** [comment]
It will go to the previous song.

**Comment by vandnakapoor19** [comment]
@melvin2016  Thanks for the reply. Currently, I am making changes in music.toml file, Where I am adding some commands.

![previous_fun](https://user-images.githubusercontent.com/45131874/76559682-fdc94a00-6475-11ea-8c31-c6edb06d73b2.png)

I am not sure how I can add a query selector. Could you please give me some idea where I can do this thing, or maybe I am missing something.

Let me know if we can set up one meeting where we can discuss this point in detail.
Thanks

**Comment by ianb** [comment]
I agree with @melvin2016, probably the best thing is just to click the previous button twice, though there's a danger that sometimes that might go back two songs if the current song hasn't played much. But we can think about that in a followup or something.

We could add a new intent "restart song" that clicked it once (though that doesn't seem very important, how often do people really want to restart?)

@vandnakapoor19 The change here should really go in `spotify/player.js` in the `action_move()` method – when it's asked to go to the previous song it should do that (by clicking twice) instead of restarting.

**Comment by melvin2016** [comment]
@vandnakapoor19  I left a tip in the chat. I hope it helps!

**Comment by melvin2016** [comment]
@vandnakapoor19 
Findings:

- I found out that there is a delay between the first click and second click because after the first click there is a delay for the selector to be active. We could use the waitForSelector() function to wait for the selector to become active after the first 

-  The previous button when clicked the first time will go 2 songs back if played within the time range of 0:00 and 0:02

**The workaround for this is given to you via chat. Please test it with it.**

**Comment by vandnakapoor19** [comment]
@ianb I've implemented the functionality and tested it on my local server. Have a look once and let me know in case anything is missing.

Thanks

**Comment by vandnakapoor19** [comment]
@ianb  I have fixed both the issues. Have a look.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 76.0a1 (2020-03-19). 
For the Youtube tab, the "Play previous" seems to not work (see #1338).

![7](https://user-images.githubusercontent.com/54401091/77078169-e3a3e480-69fe-11ea-8c1b-f135e5b75ab6.gif)
