### ISSUE TITLE
Use fuzzier intent parsing

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#657]
We should try a couple things:

- Remove "the" (other words?)
- Handle aliases for "tab", like "top" and others

Mechanically, I think we should try these substitutions alongside the original query, and score them slightly lower, but otherwise use the same scoring system that we are using.

To implement this we need a list of replacements and candidates for deletion (/cc @acwio)

**Comment by awallin** [comment]
@ianb is this something we should ask @alexandra-martin to test with a variety of fuzzy phrases?

**Comment by ianb** [comment]
We could, yes. There's only a couple substitutions now: https://github.com/mozilla/firefox-voice/commit/766c8a29048538ca4dc67694e20a8d8ebfda8746#diff-a4ad67af9cd3023b629a953b97addf0eR32-R40

So, for instance, it'll check the input phrase "close tap" and try "close tab" (the `tap: "tab"` line), and see that it's a good match. Similarly it'll try removing "the", so "close the tab" or "the close tab" will also both match. It shouldn't make those substitutions unless they seem necessary. So "search for top" shouldn't make that substitution, because it matches the search intent perfectly well without it.

**Comment by alexandra-martin** [comment]
Tried a few times with what intents there are. In general the substitutions worked for me, but in some instances transcriptions and titles are shown as the command is made, like "open (the) new tap", "close (the) tap for me", "translate (the) website/webpage to German for me", but are displayed differently in the feedback section ("open new tab", "close tab", "translate site/page to German"). I am thinking this could confuse people? Since they see variations of their command.
Also when I was saying "tap" it had a tendency to transcribe it more as "app", "this app" or "tab", but may be different to someone else.

![12 12 1](https://user-images.githubusercontent.com/54401091/70725788-af38d200-1d05-11ea-82cc-8c42a0c6c84c.gif)

![12 12 2](https://user-images.githubusercontent.com/54401091/70725797-b3fd8600-1d05-11ea-9d5d-f17d4d8f4f50.gif)

**Comment by ianb** [comment]
Yes, I believe we are using the substituted transcript throughout most of the process (and so it's what is saved in feedback), but displaying the non-substituted value. I added #756 for this.
