### ISSUE TITLE
Improve keyboard config styling

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#673]
This is what it looks like currently in  #672 (with an error):

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/44390/70272977-ceb48580-176e-11ea-929c-808bcf4f3765.png">

- [ ] Fix whitespace next to field
- [ ] Make text field bigger
- [ ] Fix whitespace generally in instructions
- [ ] Fix error message styling

**Comment by alexandra-martin** [comment]
@ianb  is it possible to have an error message when a certain shortcut can't be used, because it overwrites with another shortcut? This [shortcut list](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly ) was helpful to see what I can't use. 

![ov6](https://user-images.githubusercontent.com/54401091/70322930-20731380-1834-11ea-8e54-084362a36240.gif)
