### ISSUE TITLE
Connection error on download

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#862]
Many people are seeing the message "connection error on download" when trying to install the extension.

**Comment by awallin** [comment]
Screenshot as reported in https://github.com/mozilla/firefox_voice_community/issues/258

![image](https://user-images.githubusercontent.com/428245/74465603-8db1af00-4e4a-11ea-8c9a-75445d8c1792.png)

**Comment by jofish** [comment]
The exact error text is

**events.mozilla.og**
The add-on could not be downloaded because of a connection failure. [OK!]

This is a shot of the Console log during this error condition.


![49489772722_9123177237_o](https://user-images.githubusercontent.com/582167/74465525-68bd3c00-4e4a-11ea-87a1-cc249410f4dc.jpg)

**Comment by jofish** [comment]
The more I dig into this, the more I see this showing up as a persistent problem. 

Like, here's 1Password with their klunky workaround for it: https://support.1password.com/firefox-connection-failure/

Here's BetterTTV: https://www.reddit.com/r/firefox/comments/8l8hy1/the_addon_could_not_be_downloaded_because_of_a/

I see complaints in the comments of this blog entry: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

Another: https://www.thewindowsclub.com/add-on-could-not-be-downloaded-because-of-a-connection-failure

These people think it's some security software. But I didn't find any installed when looking it, although it does provide a direction for trying to recreate. But that doesn't sound quite right for the certificate error above. 
 https://discussions.agilebits.com/discussion/87991/the-add-on-could-not-be-downloaded-because-of-a-connection-failure

**Comment by caitmuenster** [comment]
Can you file this bug to https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions? It would be good if we could get the info from `about:support` from affected users in the bug as well.

**Comment by jofish** [comment]
Done. 

See https://bugzilla.mozilla.org/show_bug.cgi?id=1615712

Thanks

**Comment by awallin** [comment]
Another report:
https://github.com/mozilla/firefox_voice_community/issues/305

**Comment by alexandra-martin** [comment]
Bugzilla bug has been updated with the screenshots of the case where the bug was reproduced.

**Comment by alexandra-martin** [comment]
Screenshots of installation process if `extensions.install.requireBuiltInCerts` pref is added and disabled.
Tested on Windows 8.1x64 with Firefox Release 74.0 and Nightly 76.0a1 (2020-03-11).

![Win 8 1 ff nightly 76-install with pref not added](https://user-images.githubusercontent.com/54401091/76531512-fe65de80-647d-11ea-9aeb-4ae226897dfb.png)

![Win 8 1 ff nightly 76-install with pref set to true](https://user-images.githubusercontent.com/54401091/76531526-0291fc00-647e-11ea-82a5-4fe9cb6330f0.png)

![Win 8 1 ff nightly 76-install with pref set to false](https://user-images.githubusercontent.com/54401091/76531538-06258300-647e-11ea-9023-f3fed4938f95.png)

**Comment by ianb** [comment]
After some discussion, our plan to fix this is to just include instructions on the installation page, similar to what other extensions are doing, as noted in https://github.com/mozilla/firefox-voice/issues/862#issuecomment-586047630

**Comment by ianb** [comment]
It's live on the homepage:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/44390/82482093-f0df5d00-9a9b-11ea-8891-016047145b6b.png">

**Comment by awallin** [comment]
@ianb any way to generate a link that auto download? Then we can rewrite and the user won't have to open a different browser.
