### ISSUE TITLE
Tab selection

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#905]
Based on telemetry users are interested in more advanced tab management utterances such as:

"Select all tabs to the left" (would close all tabs left of the active tab)
"Select Lifehacker tab" (would only close the matching tab)
"Select the last three tabs"
"Select the first two tabs"
"Select all tabs except Spotify"
"Select all tabs without gmail"
"Select all the tabs"
"Select all tabs but this one"

**Comment by ianb** [comment]
Do we want to have any confirmation step on these?

**Comment by ianb** [comment]
Let's try all these except with "select" instead of "close". So "select all tabs to the left", etc.

Note "selected" is called "highlighted" in the API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update (but it's called selected everywhere in the UI)

I'd recommend starting with just a couple of these, specifically the ones that don't involve names (i.e., _not_ "close lifehacker tab"). So "select all tabs to the left", "select last three tabs", "select all the tabs" etc.

I'm putting this as a good first issue, but it's more like a good second issue. These will be new intents in `tab.js`

**Comment by SaumyaSinghal** [comment]
@ianb can I work on this?

**Comment by JanviMahajan14** [comment]
I would like to work on this issue .

**Comment by danielamormocea** [comment]
@ianb  can I work on this also? I've already worked in tabs.js and got the hang of it

**Comment by shreyajain25** [comment]
@ianb  Can I work on this issue.

**Comment by ianb** [comment]
I think @danielamormocea and @SaumyaSinghal both have other active issues, so yes, assigning to @shreyajain25

**Comment by shreyajain25** [comment]
Hey @ianb  just want to confirm if in this issue we need to highlight the tabs according to the query ?

**Comment by ianb** [comment]
@shreyajain25 There are some query-related selection commands in `getMatchingTabs` that @danielamormocea added, you could probably use that same routine.

**Comment by shreyajain25** [comment]
I just gave a PR #1481 ..... @ianb  Can you review it please..
Sorry, I know i got so late to it

**Comment by Simpcyclassy** [comment]
This has been merged here https://github.com/mozilla/firefox-voice/pull/1743
