### ISSUE TITLE
Can't handle calculation

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#918]
Reported by users and I was able to validate.

5-2 correctly returns the calculator card provided by Google but 5 - 2 executes a search and returns a page "The Beginner's Guide to the 5:2 Diet"

**Comment by ianb** [comment]
This is an intent parser bug that I kind of fixed, but not enough. Punctuation gets eliminated, but in this case we don't want that.

#728 would fix this, but we can also probably fix it in a more expedient way by not removing punctuation that stands alone (in this case "-" with no letters near it).

**Comment by ianb** [comment]
I thought the search was the problem, but apparently Google has opinions on whitespace itself. [This search](https://www.google.com/search?safe=active&ei=Sp1WXsjPJsO4tQayhb3wAw&q=5-2&oq=5-2&gs_l=psy-ab.3..0i67j0j0i67j0j0i7i30l2j0j0i7i30j0l2.3002.3722..3922...1.0..0.85.227.3......0....1..gws-wiz.......0i273.k-7-NViGwxQ&ved=0ahUKEwjInNCM0u_nAhVDXM0KHbJCDz4Q4dUDCAo&uact=5) (for `5-2`) gives a calculator. But [this search](https://www.google.com/search?safe=active&ei=T51WXse8EpfctAbGk6WIDg&q=5+-+2&oq=5+-+2&gs_l=psy-ab.3..0j0i7i30l2j0j0i7i30j0l3j0i7i30j0.77780.77980..78286...1.0..0.102.271.2j1......0....1..gws-wiz.......0i67.HDnGgJ7QEEk&ved=0ahUKEwiHoO2O0u_nAhUXLs0KHcZJCeEQ4dUDCAo&uact=5) (for `5 - 2`) does not.

I'm baffled. The same thing is true for `+`. But not `/` (e.g., say "10 divided by 12"). Note that Google STT always returns spaces around the operators, so it's an active issue. `*` also works.

I'm inclined to do some transformation like `/(\d+)\s+([+-])\s+(\d+)/` just for the case of some search, just because it literally breaks all attempts to calculate sums and differences.
