### ISSUE TITLE
Dictate into text/input fields

### ISSUE THREAD

**Issue by jtaylor113** [mozilla/firefox-voice#930]
I would like to be able to enter text within text boxes in websites via voice instead of keyboard. Basically, voice to text entry.

**Comment by awallin** [comment]
Thanks @madb1lly @jtaylor113. Moving this issue to our development repo for prioritization.

**Comment by ianb** [comment]
A couple things we'll have to figure out:

## What field do we type into?

The `paste` intent has some heuristics for this currently. Basically if a text field is focused (input, textarea, or something with contenteditable) then we just type into that. But if not, then it tries to find a proper field. It prefers textarea and contenteditable to an input field, mostly because search fields are commonly the first field but aren't a good "content" field and seem less likely to be a target.

I think an additional heuristic would be to look for a visible field. E.g., on this page if you are scrolled to the top then the only input visible is the search field, and I think that's a reasonable default. If you are at the bottom then this comment field is visible. Of course on a shorter ticket they could both be visible, and by prioritizing a textarea then the comment will be selected.

Focus-changing commands would be helpful ("focus next field", "focus [query] field" etc – query would search against labels, id/names, and placeholders).

## How is text entered?

Probably the easiest way is to put the text into the clipboard, then use `document.execCommand("paste")`. This let's the other systems do their work. The downside is that we clobber the clipboard.

The [Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) APIs do allow reading and writing in such a way that we could replace and then put back the clipboard contents, but those aren't fully implemented. Maybe we could do it in an experiment (since we've started using those). But not the place to start (though I'm interested in using the clipboard as our gateway into many pages, so it would be worth doing something eventually).

We could enter text by setting `.value` or `.innerHTML` (on contenteditable), but this is wonky in my experience. I think it would be better to clobber the clipboard and get a fully working experience.

**Comment by jtaylor113** [comment]
@ianb - The focus problem is why I mentioned the possibility of right-clicking within the field and choosing dictate from a context menu. You would not lose focus on the text box you are entering text into.

**Comment by ianb** [comment]
Something has landed (#930):

- "Enter text this is a test"
- "Focus username field"
- "Focus next/previous"

It directly modifies the values of input fields, and appends, so it won't respect cursor position. An alternative would have been to paste. But I also wanted to handle whitespace cleanly (so entering text multiple times won't run words together), which pasting doesn't really work for either.

There are probably additional phrases we should match.
