### ISSUE TITLE
Add Deezer (music service)

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#964]
I've seen on issues and nobody asked to add Deezer as music service.

**Comment by IkkyOdufade** [comment]
Hi @ianb . Can I work on this?

**Comment by ianb** [comment]
@IkkyOdufade You got it! You'll want to look at how `services/spotify` works and do something similar.

**Comment by IkkyOdufade** [comment]
Thank you :). Would do that..

**Comment by IkkyOdufade** [comment]
Hi @ianb . I'm having some issues with my code. So first, for deezer, you cant search without login or signing up, unlike spotify. So how do I go about it? 

 Secondly, the firefox-voice extension on my firefox-nightly is not responding to voice commands again. It is giving me so many errors :(.
![Annotation 2020-03-11 174045](https://user-images.githubusercontent.com/47696080/76442037-98675180-63c0-11ea-85af-67eb29c917a2.png)

**Comment by ianb** [comment]
@IkkyOdufade You might want to check out what @melvin2016 did in #1192 for SoundCloud. The MusicPlayer class he added would be good to use for this too.

Are you having a problem where the microphone just doesn't seem to respond? That's something we've gotten reports about but haven't been able to understand a lot about. If so we'd be interested to know what's going on (I created [Bug 1621462](https://bugzilla.mozilla.org/show_bug.cgi?id=1621462) for Firefox about this).

If that is the problem then note you can also type commands, simply start typing when the popup is open. None of the errors or warnings in that screenshot look too concerning – it can be a bit distracting because it's the logging for the entire browser, including things that have nothing to do with Firefox Voice. 

Lastly, the login issue: if there's a login screen you should just focus the screen and give an error "please login first". We don't need to handle it in Firefox Voice, we should just alert the user to the issue and focus the tab.

**Comment by IkkyOdufade** [comment]
Ok, thank you. I'll finish it tonight.
