### ISSUE TITLE
Add voice command "Open NAME extension"

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#976]
I think it's a good idea add a voice command to open an extension just with the voice.
For example. I installed uBlock. If I want to open it, i should click the icon on address bar.
So, why don't add "Open uBlock extension" voice command to do the same thing?

**Comment by ianb** [comment]
This is going to be hard on a couple levels – invoking another extension isn't clear, but it probably means click the accompanying toolbar button. That's not something that we easily have access to. But then once you've done that you have a popup, and an extension popup is impossible for us to control at all, so you would be forced to continue interacting with your mouse and not your voice.

Because of this, we don't think this will be a useful experience for someone.

Note that we are very open to allowing other extensions to be controlled by voice, if those extensions want to add code to their own extension to run those commands.
