### ISSUE TITLE
[Telemetry] 14 day retention

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#990]
To compare Firefox Voice retention to know retention rates from other products we should add a metric to the dashboard showing usage between 7-14 days post installation.

@jofish Are there specific details you want to include to define this metric?

**Comment by ianb** [comment]
Here's an example query from another project:

```sql

/* This query was auto-transformed for BigQuery from https://sql.telemetry.mozilla.org/queries/56972 */

--Filter down to a resultset of client_id, os, and week
WITH clients AS (
  SELECT
    F.client_id,
    date_trunc(submission_date, week(monday)) as week
  FROM telemetry.telemetry_core_parquet F
  WHERE --F.channel = 'release'
  F.os = 'Android'
  AND F.app_name LIKE 'FirefoxReality_%'
  AND submission_date >= date '2018-06-20'
),

-- We could do this in the previous SELECT but we'd be repeating ourselves a lot.
-- 1 row per client, os, week seen, assigning each client to a "cohort" week by their min. week seen
distinct_clients AS (
  SELECT
    count(*) as n,
    client_id,
    week,
    MIN(week) OVER (PARTITION BY client_id) AS cohort
  FROM clients
  GROUP BY client_id, week
) 
-- have to misname columns for redash cohort viz to work
SELECT
    cohort as date
    , week  -- as date
    , MAX(COUNT(*)) OVER (PARTITION BY cohort) as total  -- cohort_size
    , RANK() OVER (PARTITION BY COHORT ORDER BY WEEK ASC) - 1 as day_number  -- week_num
    , COUNT(*) as value  -- active_users
    -- date, day_number, value, total
FROM distinct_clients
GROUP BY cohort, week
ORDER by cohort, week
```

**Comment by jofish** [comment]
Sean suggested:I've been having conversations with several of you about what success looks like for some of our product experiments.  Hadn't heard this number specifically before but saw a note in the mobile OKR efforts that said day 7 retention of 20% was industry standard for successful new product. I can imagine that's different when there's a different cadence or use case both worth considering.On Feb 12, 2020, at 12:35 PM, Abraham Wallin <notifications@github.com> wrote:To compare Firefox Voice retention to know retention rates from other products we should add a metric to the dashboard showing usage between 7-14 days post installation.@jofish Are there specific details you want to include to define this metric?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ianb** [comment]
Created here: https://sql.telemetry.mozilla.org/queries/68765/source#173654 (note: not public)
